version: '3.7'

services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        container_name: redenda-api
        expose:
            - '3333'
        ports:
            - '3333:3333'
        command: npm run start
